# Generated by Django 4.0.2 on 2022-02-02 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0002_customuser_is_congressman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meet_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('variant_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('voting_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congress.variant')),
            ],
        ),
        migrations.AddField(
            model_name='variant',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congress.voting'),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('claim_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('photo', models.FileField(blank=True, upload_to='')),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('agenda_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congress.meeting')),
            ],
        ),
    ]
