# Generated by Django 4.0.2 on 2022-02-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0003_meeting_variant_voting_vote_variant_voting_claim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='title',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='title',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voting',
            name='title',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
