# Generated by Django 4.0.2 on 2022-02-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0005_remove_variant_voting_alter_agenda_agenda_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantsvoting',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='variantsvoting',
            name='voting',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='variant',
        ),
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vote',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Против'), ('y', 'За'), ('a', 'Воздержался')], default='m', help_text='Вариант ответа', max_length=1),
        ),
        migrations.DeleteModel(
            name='Variant',
        ),
        migrations.DeleteModel(
            name='VariantsVoting',
        ),
    ]
