# Generated by Django 4.0.2 on 2022-02-02 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0006_remove_variantsvoting_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='congress.voting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Против'), ('a', 'Воздержался'), ('y', 'За')], default='m', help_text='Вариант ответа', max_length=1),
        ),
    ]
