# Generated by Django 4.0.2 on 2022-02-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0007_vote_voting_alter_vote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Воздержался'), ('n', 'Против'), ('y', 'За')], default='m', help_text='Вариант ответа', max_length=1),
        ),
    ]
