# Generated by Django 4.0.2 on 2022-02-03 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0009_alter_vote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='congress.meeting'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vote',
            name='status',
            field=models.CharField(blank=True, choices=[('y', 'За'), ('n', 'Против'), ('a', 'Воздержался')], default='m', help_text='Вариант ответа', max_length=1),
        ),
    ]
