# Generated by Django 4.0.2 on 2022-02-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0010_voting_meeting_alter_claim_photo_alter_vote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Против'), ('a', 'Воздержался'), ('y', 'За')], default='m', help_text='Вариант ответа', max_length=1),
        ),
    ]
