# Generated by Django 4.0.2 on 2022-02-03 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congress', '0012_alter_vote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
